### ISSUE TITLE
Unable to install URDF Importer Package

### ISSUE THREAD

**Issue by saratrajput** [Unity-Technologies/Robotics-Object-Pose-Estimation#22]
Hello. I'm working on Ubuntu 20 with UnityHub 2.4.2 and Unity Editor 2020.2.7f1. When I try to install the URDF Importer Package: ```https://github.com/Unity-Technologies/URDF-Importer.git?path=/com.unity.robotics.urdf-importer#v0.2.0```, I get the following errors:
- ```Script 'Joint' has the same name as built-in Unity component.
AddComponent and GetComponent will not work with this script.```
- ```Library/PackageCache/com.unity.robotics.urdf-importer@f663d6f959/Runtime/Controller/JointControl.cs(15,12): error CS0246: The type or namespace name 'ArticulationBody' could not be found (are you missing a using directive or an assembly reference?)```
- ```Library/PackageCache/com.unity.robotics.urdf-importer@f663d6f959/Runtime/Controller/FKRobot.cs(12,21): error CS0246: The type or namespace name 'ArticulationBody' could not be found (are you missing a using directive or an assembly reference?)```
- ```Library/PackageCache/com.unity.robotics.urdf-importer@f663d6f959/Runtime/UrdfComponents/UrdfJoints/UrdfJointPrismatic.cs(23,17): error CS0246: The type or namespace name 'ArticulationDrive' could not be found (are you missing a using directive or an assembly reference?)```
- ```Library/PackageCache/com.unity.robotics.urdf-importer@f663d6f959/Runtime/Controller/Controller.cs(13,17): error CS0246: The type or namespace name 'ArticulationBody' could not be found (are you missing a using directive or an assembly reference?)```

**Comment by mrpropellers** [comment]
Hey @saratrajput, the first warning can be safely ignored; this is a longstanding naming conflict that I *believe* we already have a fix in dev for, and if it not it's coming soon!

The rest of the errors indicate some problem with resolution of dependencies for the URDF Importer. One quick thing to try is to simply delete the PackageCache, do a `git submodule update --init --recursive` at the repository root, check the Packages/manifest.json in the project to ensure the string specified for URDF-Importer matches exactly with what's in the tutorial, and re-open Unity. This is the naive solution though, so I will follow up with some colleagues internally to see if this is a known issue with a more targeted fix.

**Comment by saratrajput** [comment]
Thanks. But actually a couple of hours ago I realized that the project I had created was with 2018.4.30f1 by mistake as I have multiple Unity Editors in my hub. With 2020.2.7f1, the package installation goes smoothly. I'll close this issue now.
